### ISSUE TITLE
Ejercicios de las siguientes clases

### ISSUE THREAD

**Issue by checor** [rctorr/bedu#3]
Hola!

¿Existe interés por desarrollar los ejercicios de las siguientes clases?

Yo tengo algunos, puedo lanzar un PR si desean, pero pregunto para si es así, darles mejor formato y comentarlos.

Saludos!

**Comment by checor** [comment]
Ya vi que se encuentran en otras ramas

**Comment by fleiz** [comment]
@checor igual si tienes material interesante o ejemplos que consideras pueden servir puedes realizar PR. 
Saludos!
